# 配置MySQL数据库的连接参数
spring: 
   datasource: 
      url: jdbc:mysql://127.0.0.1:3306/zzw01?useSSL=false&serverTimezone=CST&allowPublicKeyRetrieval=true
      username: zzw01
      password: 1234
      
   jpa: 
# 自动生产DDL语句（数据定义语言），用于实现表结构自动创建
      generate-ddl: true
# 显示每个SQL在日志里面
      show-sql: true
      
   # 配置Redis的连接信息
   redis: 
      host: 120.77.251.143
      port: 6379
      database: 3
   
   
# 修改运行时的端口号，因为一个端口号只能被一个人使用。
# 如果多个人使用一台服务器，自然要使用不同的端口！
# 删除WEB功能，就不需要server.port参数
#server.port: 8036